### ISSUE TITLE
Push not working

### ISSUE THREAD

**Issue by daviddelucca** [NeuraLabs/NeuraSampleAndroid#1]
Hello folks!

How can I check why push notification is not being delivered by Neura? If I send push from FCM direct to token received on Android, it works. Anyone could give me a hand to identify why it won't work when comes from Neura?

Thanks

**Comment by youvalv** [comment]
Hi David!

Can you give some more details? did you open a new app on the Neura [console](http://dev.theneura.com/console/apps)?
did you log in to the devsite using the phone number you used to login in the app?

you can simulate event using UI in the SDK by calling [simulateAnEvents()](http://docs.theneura.com/android/com/neura/standalonesdk/service/NeuraApiClient.html#simulateAnEvent--)

You can contact me directly by emailing dev-support@theneura.com

Youval
