### ISSUE TITLE
Subscribe to moment error

### ISSUE THREAD

**Issue by ashishthakur08nov** [NeuraLabs/NeuraSampleAndroid#9]
Successfully  integrate sdk get user access token and user id,
when subscribe to any moment with unique  identifier it fails..

giving error:- Request entity expected but not supplied

Request body:-
https://wapi.theneura.com/v1/subscriptions?event_name=userLeftCafe&method=push&identifier=ut3l5nk8lsa904vNO7e_9977&state=testing&webhook_id=webhook

**Comment by youvalv** [comment]
Hi

I edited your comment and removed the token, for security reasons
Also, I received your support ticket in https://support.theneura.com which is the appropriate channel for this kind of requests. closing the issue here

For future reference:

solution in the last comment

**Comment by ashishthakur08nov** [comment]
Can u just help me out what i am doing wrong when subscribing moments
already mentioned the details on support ticket, other api is working
properly.

**Comment by youvalv** [comment]
we are checking your support ticket and we'll reply to that

Thanks

**Comment by ashishthakur08nov** [comment]
Yes please thanks for the quick response.

**Comment by youvalv** [comment]
for future reference:
1. Subscriptions are a POST call
2. In  POST method requests, parameters should be placed in the body and not in the URL (as opposed to GET method)
3. please add the parameters in the body of the request in a json format with content type header application/json 
4. please note that you used "method":"push" but gave a webhook ID - If you want the moment to get to a webhook use "method":"webhook"
